version: "3"

services:
  db:
    container_name: juegonaves_database
    image: mysql
    restart: always
    volumes:
      - ./juegonaves:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=juegonaves
      - MYSQL_DATABASE= juegonaves
